layout_spectrum: 0.185134
color:
  saturation: 0.9317572
  brandStrength: 1
  lightness: 0.8057116
  rhythmicContrast: 0.445193
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.8369112
name: Hbiz
